language: R
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

before_script:
    - chmod +x ./_build.sh
    - chmod +x ./_deploy.sh
    
script:
    - ./_build.sh
    - ./_deploy.sh
