language: R
sudo: true
cache: packages
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
    - libudunits2-dev
    - libgdal-dev
    - libgeos-dev 
    - libproj-dev 
    
before_script:
    - chmod +x ./_build.sh
    - chmod +x ./_deploy.sh
    
script:
    - ./_build.sh
    - ./_deploy.sh
